# Support Vector Mahine with wine-quality
- SVM 실습 (D조)
- 2018년 11월 8일

## 1. Import packages
### 필요한 패키지들 import
- np, plt, pd

In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Import the dataset
- 파일 경로 각자 맞춰서 설정

In [69]:
df = pd.read_csv("./winequality/winequality-data.csv")

In [70]:
# 불러들여온 csv 파일 확인
df.head()

fixed.acidity  volatile.acidity  citric.acid  residual.sugar  chlorides  \
0            6.7              0.15         0.38             1.7      0.037   
1            6.7              0.44         0.31             1.9      0.030   
2            6.1              0.17         0.21             1.9      0.090   
3            6.6              0.39         0.22             4.0      0.038   
4            6.8              0.32         0.34             6.0      0.050   

   free.sulfur.dioxide  total.sulfur.dioxide  density    pH  sulphates  \
0                 20.0                  84.0  0.99046  3.09       0.53   
1                 41.0                 104.0  0.99000  3.29       0.62   
2                 44.0                 130.0  0.99255  3.07       0.41   
3                 17.0                  98.0  0.99018  3.25       0.53   
4                  5.0                 129.0  0.99530  3.19       0.40   

   alcohol  quality   id  
0     11.4        6  981  
1     12.6        7  982  
2      9.7        5  983  
3     13.0        7  984  
4      9.1        5  985

In [71]:
X = df.iloc[:,2:]
y = df.iloc[:,1]

## 2. Data Preprocessing

### 데이터 확인
- 각 데이터의 결측치, 비어있는 값 등을 확인해본다. 
- 쓸모 없는 값은 버리거나(drop) 채우거나 ?
- 숫자 데이터가 아닌 값들은 숫자로 바꿔준다든지?

In [13]:
pd.isna(df)

fixed.acidity  volatile.acidity  citric.acid  residual.sugar  chlorides  \
0             False             False        False           False      False   
1             False             False        False           False      False   
2             False             False        False           False      False   
3             False             False        False           False      False   
4             False             False        False           False      False   
5             False             False        False           False      False   
6             False             False        False           False      False   
7             False             False        False           False      False   
8             False             False        False           False      False   
9             False             False        False           False      False   
10            False             False        False           False      False   
11            False             False        False           False      False   
12            False             False        False           False      False   
13            False             False        False           False      False   
14            False             False        False           False      False   
15            False             False        False           False      False   
16            False             False        False           False      False   
17            False             False        False           False      False   
18            False             False        False           False      False   
19            False             False        False           False      False   
20            False             False        False           False      False   
21            False             False        False           False      False   
22            False             False        False           False      False   
23            False             False        False           False      False   
24            False             False        False           False      False   
25            False             False        False           False      False   
26            False             False        False           False      False   
27            False             False        False           False      False   
28            False             False        False           False      False   
29            False             False        False           False      False   
...             ...               ...          ...             ...        ...   
3883          False             False        False           False      False   
3884          False             False        False           False      False   
3885          False             False        False           False      False   
3886          False             False        False           False      False   
3887          False             False        False           False      False   
3888          False             False        False           False      False   
3889          False             False        False           False      False   
3890          False             False        False           False      False   
3891          False             False        False           False      False   
3892          False             False        False           False      False   
3893          False             False        False           False      False   
3894          False             False        False           False      False   
3895          False             False        False           False      False   
3896          False             False        False           False      False   
3897          False             False        False           False      False   
3898          False             False        False           False      False   
3899          False             False        False           False      False   
3900          False             False

In [49]:
df['quality'].value_counts().sort_values(ascending=False)

6    1752
5    1163
7     707
8     140
4     134
3      17
Name: quality, dtype: int64

In [50]:
lab_enc = preprocessing.LabelEncoder()
y_encoded = lab_enc.fit_transform(y)
print(y_encoded)
print(utils.multiclass.type_of_target(y_train))
print(utils.multiclass.type_of_target(y_train.astype('int')))
print(utils.multiclass.type_of_target(y_encoded))

[13 69 17 ... 18 25 73]
multiclass
multiclass
multiclass


## Split into train, validation, test set
- 전처리를 끝내고 난 뒤에는 데이터를 train, validation, test set 으로 나눠준다. 

In [72]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

# 전체 data set을 (training + validation), test으로 나눔
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, train_size=0.8, random_state = 0)


# (training + validation) set을 training, validation으로 나눔
X_train, X_valid, y_train, y_valid = train_test_split(X_train,y_train, train_size=0.75, random_state = 0)

# 각 세트의 크기를 출력한다. 
print("size of training set: %d,  size of validation set: %d,  size of test set: %d" % (
        X_train.shape[0], X_valid.shape[0], X_test.shape[0]))

size of training set: 2347,  size of validation set: 783,  size of test set: 783


C:\Users\wjssm\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


## 3. Test with validation set

In [73]:
from sklearn.svm import SVC

In [74]:
clf = SVC()
clf.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [65]:
y_train

array([45, 51, 45, ..., 47, 27, 29], dtype=int64)

In [66]:
y_predict = clf.predict(X_test)

In [67]:
y_predict

array([33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 23, 33, 33, 33

In [23]:
from sklearn import preprocessing
from sklearn import utils

In [34]:
lab_enc = preprocessing.LabelEncoder()
y_train_encoded = lab_enc.fit_transform(y_train)
print(training_scores_encoded)
print(utils.multiclass.type_of_target(y_train))
print(utils.multiclass.type_of_target(y_train.astype('int')))
print(utils.multiclass.type_of_target(y_train_encoded))

[43 49 43 ... 45 25 27]
continuous
binary
multiclass


In [35]:
utils.multiclass.type_of_target(y_train_encoded)

'multiclass'

In [36]:
clf = SVC()
clf.fit(X_train,y_train_encoded)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
lab_enc = preprocessing.LabelEncoder()
y_test_encoded = lab_enc.fit_transform(y_train)
print(training_scores_encoded)
print(utils.multiclass.type_of_target(y_train))
print(utils.multiclass.type_of_target(y_train.astype('int')))
print(utils.multiclass.type_of_target(y_train_encoded))

In [ ]:
clf.predict(X_test,)

In [ ]:
# training set과 validation set을 합쳐 모델을 다시 만든 후 
# test set을 이용하여 모델을 평가 

## 4. Test with  Cross Validation 
- 위의 결과를 참고해서 grid search를 진행합니다.
- parma_grid의 gamma와 C 값을 임의로 넣고 돌려보세요


In [ ]:
param_grid = {'C':[                   ] ,
              'gamma':[                 ] } 
param_grid

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC


grid_search = 


# overfitting 방지를 위해 training, test set으로 나눔



# fit



print("최적 매개변수 : ",grid_search.best_params_) 
print("최상 교차검증 점수 : ",grid_search.best_score_) 
print("최고 성능 모델 : ",grid_search.best_estimator_)

### 결과 확인


In [ ]:
import pandas as pd
from IPython.display import display

results = pd.DataFrame(grid_search.cv_results_)
display(results)

In [ ]:
import mglearn
import matplotlib.pyplot as plt

scores = [score.mean_validation_score for score in grid_search.grid_scores_]
scores = np.array(scores).reshape( , ) 
# reshape의  숫자는 gamma와 C 의 개수에 맞춰주세요 

mglearn.tools.heatmap(scores, xlabel='gamma', ylabel='C', xticklabels=param_grid['gamma'], yticklabels=param_grid['C'], cmap="viridis")
plt.show()

# Accuracy = ? 
- grid_search.best_score_ 