In [1]:
import numpy as np

In [8]:
test=[[1,2,3,4],[5,6,7,8]]
np.array(test).shape

(2, 4)

In [13]:
np.array(test).reshape(-1,2).shape

(4, 2)

In [20]:
test=[[1,2,3,4],[5,6,7,8],[1,2,3,4],[1,2,3,4]]
np.array(test).shape

(4, 4)

In [23]:
np.array(test).reshape(2,2,4).flatten().shape

(16,)

In [26]:
np.arange(0,10,0.5).reshape(10,-1)

array([[0. , 0.5],
       [1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5],
       [5. , 5.5],
       [6. , 6.5],
       [7. , 7.5],
       [8. , 8.5],
       [9. , 9.5]])

In [29]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
test


[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [1, 2, 3, 4]]

In [33]:
np.ones_like(test)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])